include:
  - project: git-srv/pipelines
    ref: main
    file: Docker.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  DS_EXCLUDED_ANALYZERS: "gemnasium-maven, gemnasium-python, bundler-audit, retire.js"

container_scanning:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  variables:
    DOCKER_IMAGE: $CI_REGISTRY_IMAGE:edge

gemnasium-dependency_scanning:
  needs: []

license_scanning:
  needs: []
